on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1.1.2
      env:
        SOURCE_REPO: "git@github.com:zhboat/cdn_pic.git"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: "git@e.coding.net:zhboat/pic.git"
        DESTINATION_BRANCH: "master"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
